collapse-control-flow:
- changed-files:
  - any-glob-to-any-file:
    - '**/IfExpressionExt.kt'
    - '**/TernaryExpressionExt.kt'

collapse-pattern-matching:
- changed-files:
  - any-glob-to-any-file:
    - '**/PatternMatchingExt.kt'
collapse-try-statements:
- changed-files:
  - any-glob-to-any-file:
    - '**/PsiTryStatementExt.kt'

collapse-declaration:
- changed-files:
  - any-glob-to-any-file:
    - '**/AssignmentExpressionExt.kt'
    - '**/VariableDeclarationExpressionExt.kt'

collapse-literals:
- changed-files:
  - any-glob-to-any-file:
    - '**/ConcatenationExpressionExt.kt'
    - '**/NumberLiteralExpressionExt.kt'
    - '**/StringLiteralExpressionExt.kt'

collapse-methods:
- changed-files:
  - any-glob-to-any-file:
    - '**/MethodCallExpressionExt.kt'

collapse-single-expression-functions:
- changed-files:
  - any-glob-to-any-file:
    - '**/SingleExpressionFunctionExt.kt'

collapse-operators:
- changed-files:
  - any-glob-to-any-file:
    - '**/BinaryExpressionExt.kt'
    - '**/PolyadicExpressionExt.kt'
    - '**/PrefixExpressionExt.kt'

collapse-println:
- changed-files:
  - any-glob-to-any-file:
    - '**/PrintlnExt.kt'
collapse-type-casts:
- changed-files:
  - any-glob-to-any-file:
    - '**/PsiTypeCastExpressionExt.kt'

collapse-slicing:
- changed-files:
  - any-glob-to-any-file:
    - '**/ArrayAccessExpressionExt.kt'

collapse-logger-brackets:
- changed-files:
  - any-glob-to-any-file:
    - '**/LoggerBracketsExt.kt'

field-shift:
- changed-files:
  - any-glob-to-any-file:
    - '**/FieldShift*'

lombok:
- changed-files:
  - any-glob-to-any-file:
    - '**/LombokState.kt'
    - '**/PsiMethodExt.kt'
    - '**/lombok/**'

pseudo-annotations:
- changed-files:
  - any-glob-to-any-file:
    - 'pseudo/**'

state:
- changed-files:
  - any-glob-to-any-file:
    - '**/AdvancedExpressionFoldingSettings.kt'
    - '**/*State.kt'

tests:
- changed-files:
  - any-glob-to-any-file:
    - '**/*Test*'

documentation:
- changed-files:
  - any-glob-to-any-file:
    - '**/*.md'

github-actions:
- changed-files:
  - any-glob-to-any-file:
    - '.github/workflows/**'

gradle:
- changed-files:
  - any-glob-to-any-file:
    - 'build.gradle.kts'
    - 'settings.gradle.kts'

integration-layer:
- changed-files:
  - any-glob-to-any-file:
    - '**/integration/**'

action:
- changed-files:
  - any-glob-to-any-file:
    - 'src/com/intellij/advancedExpressionFolding/action/**'

settings-ui:
- changed-files:
  - any-glob-to-any-file:
    - 'src/com/intellij/advancedExpressionFolding/view/**'

plugin-xml:
- changed-files:
  - any-glob-to-any-file:
    - 'resources/META-INF/*.xml'

scripts:
- changed-files:
  - any-glob-to-any-file:
    - 'scripts/**'

examples-data:
- changed-files:
  - any-glob-to-any-file:
    - 'examples/data/**'

test-data:
- changed-files:
  - any-glob-to-any-file:
    - 'testData/**'

folded-expected:
- changed-files:
  - any-glob-to-any-file:
    - 'folded/**'

wiki:
- changed-files:
  - any-glob-to-any-file:
    - 'wiki/**'
    - 'wiki-clone/**'

labeler:
- changed-files:
  - any-glob-to-any-file:
    - '.github/labeler.yml'

gradle-wrapper:
- changed-files:
  - any-glob-to-any-file:
    - 'gradlew'
    - 'gradlew.bat'
    - 'gradle/wrapper/**'

