collapse-control-flow:
- changed-files:
  - any-glob-to-any-file:
    - '**/IfExpressionExt.kt'
    - '**/TernaryExpressionExt.kt'

collapse-loop-statements:
- changed-files:
  - any-glob-to-any-file:
    - '**/LoopExt.kt'
    - '**/ForStatementExpressionExt.kt'
    
collapse-constructor-references:
- changed-files:
  - any-glob-to-any-file:
    - '**/ConstructorReferenceExt.kt'
    - '**/MethodReferenceExt.kt'
    
collapse-pattern-matching:
- changed-files:
  - any-glob-to-any-file:
    - '**/PatternMatchingExt.kt'
    
collapse-try-statements:
- changed-files:
  - any-glob-to-any-file:
    - '**/PsiTryStatementExt.kt'

collapse-declaration:
- changed-files:
  - any-glob-to-any-file:
    - '**/AssignmentExpressionExt.kt'
    - '**/VariableDeclarationExpressionExt.kt'

collapse-literals:
- changed-files:
  - any-glob-to-any-file:
    - '**/ConcatenationExpressionExt.kt'
    - '**/NumberLiteralExpressionExt.kt'
    - '**/StringLiteralExpressionExt.kt'

collapse-methods:
- changed-files:
  - any-glob-to-any-file:
    - '**/MethodCallExpressionExt.kt'

collapse-default-params:
- changed-files:
  - any-glob-to-any-file:
    - '**/MethodDefaultParameterExt.kt'
    
collapse-null-safety:
- changed-files:
  - any-glob-to-any-file:
    - '**/IfNullSafeExt.kt'
    - '**/NullableExt.kt'
    
collapse-single-expression-functions:
- changed-files:
  - any-glob-to-any-file:
    - '**/SingleExpressionFunctionExt.kt'

collapse-operators:
- changed-files:
  - any-glob-to-any-file:
    - '**/BinaryExpressionExt.kt'
    - '**/PolyadicExpressionExt.kt'
    - '**/PrefixExpressionExt.kt'

collapse-println:
- changed-files:
  - any-glob-to-any-file:
    - '**/PrintlnExt.kt'
collapse-type-casts:
- changed-files:
  - any-glob-to-any-file:
    - '**/PsiTypeCastExpressionExt.kt'

collapse-slicing:
- changed-files:
  - any-glob-to-any-file:
    - '**/ArrayAccessExpressionExt.kt'

collapse-logger-brackets:
- changed-files:
  - any-glob-to-any-file:
    - '**/LoggerBracketsExt.kt'

field-shift:
- changed-files:
  - any-glob-to-any-file:
    - '**/FieldShift*'

lombok:
- changed-files:
  - any-glob-to-any-file:
    - '**/LombokState.kt'
    - '**/PsiMethodExt.kt'
    - '**/lombok/**'

pseudo-annotations:
- changed-files:
  - any-glob-to-any-file:
    - 'pseudo/**'

state:
- changed-files:
  - any-glob-to-any-file:
    - '**/AdvancedExpressionFoldingSettings.kt'
    - '**/*State.kt'

tests:
- changed-files:
  - any-glob-to-any-file:
    - '**/*Test*'

documentation:
- changed-files:
  - any-glob-to-any-file:
    - '**/*.md'

docs-readme:
- changed-files:
  - any-glob-to-any-file:
    - 'README.md'

docs-changelog:
- changed-files:
  - any-glob-to-any-file:
    - 'CHANGELOG.md'

docs-contributing:
- changed-files:
  - any-glob-to-any-file:
    - 'CONTRIBUTING.md'

docs-policy:
- changed-files:
  - any-glob-to-any-file:
    - 'CODE_OF_CONDUCT.md'
    - 'SECURITY.md'
    - 'SUPPORT.md'

docs-guides:
- changed-files:
  - any-glob-to-any-file:
    - 'docs/**'

github-actions:
- changed-files:
  - any-glob-to-any-file:
    - '.github/workflows/**'

github-config:
- changed-files:
  - any-glob-to-any-file:
    - '.github/CODEOWNERS'
    - '.github/dependabot.yml'
    - '.github/pull_request_template.md'

github-issue-templates:
- changed-files:
  - any-glob-to-any-file:
    - '.github/ISSUE_TEMPLATE/**'

gradle:
- changed-files:
  - any-glob-to-any-file:
    - 'build.gradle.kts'
    - 'settings.gradle.kts'

integration-test:
- changed-files:
  - any-glob-to-any-file:
    - '**/integration/**'
    - '.github/workflows/integration-test.yml'

action:
- changed-files:
  - any-glob-to-any-file:
    - 'src/com/intellij/advancedExpressionFolding/action/**'

settings-ui:
- changed-files:
  - any-glob-to-any-file:
    - 'src/com/intellij/advancedExpressionFolding/view/**'
    - 'src/com/intellij/advancedExpressionFolding/settings/view/**'

plugin-xml:
- changed-files:
  - any-glob-to-any-file:
    - 'resources/META-INF/*.xml'

resources-bundle:
- changed-files:
  - any-glob-to-any-file:
    - 'resources/Bundle.properties'

resources-intentions:
- changed-files:
  - any-glob-to-any-file:
    - 'resources/intentionDescriptions/**'

scripts:
- changed-files:
  - any-glob-to-any-file:
    - 'scripts/**'

examples-data:
- changed-files:
  - any-glob-to-any-file:
    - 'examples/data/**'

examples-gradle:
- changed-files:
  - any-glob-to-any-file:
    - 'examples/gradlew'
    - 'examples/gradlew.bat'
    - 'examples/settings.gradle.kts'

test-data:
- changed-files:
  - any-glob-to-any-file:
    - 'testData/**'

folded-expected:
- changed-files:
  - any-glob-to-any-file:
    - 'folded/**'

wiki:
- changed-files:
  - any-glob-to-any-file:
    - 'wiki/**'
    - 'wiki-clone/**'

labeler:
- changed-files:
  - any-glob-to-any-file:
    - '.github/labeler.yml'

gradle-wrapper:
- changed-files:
  - any-glob-to-any-file:
    - 'gradlew'
    - 'gradlew.bat'
    - 'gradle/wrapper/**'

class-advanced-expression-folding-builder:
- changed-files:
  - any-glob-to-any-file:
    - 'src/com/intellij/advancedExpressionFolding/AdvancedExpressionFoldingBuilder.kt'

class-advanced-expression-folding-settings:
- changed-files:
  - any-glob-to-any-file:
    - 'src/com/intellij/advancedExpressionFolding/settings/AdvancedExpressionFoldingSettings.kt'

class-settings-configurable:
- changed-files:
  - any-glob-to-any-file:
    - 'src/com/intellij/advancedExpressionFolding/settings/view/SettingsConfigurable.kt'

class-checkboxes-provider:
- changed-files:
  - any-glob-to-any-file:
    - 'src/com/intellij/advancedExpressionFolding/settings/view/CheckboxesProvider.kt'

class-dynamic-data-provider:
- changed-files:
  - any-glob-to-any-file:
    - 'src/com/intellij/advancedExpressionFolding/processor/methodcall/dynamic/IDynamicDataProvider.kt'

