package data[0:";"]

public class ControlFlowMultiStatementTestData {
    public static void main(String[] args) {
        if [1:"("]args.length > 0[1:")"] [19:"{"]
                [20:"System.out."]println([21:"\"...\""])[22:";"]
        [23:"System.out."]println([24:"\"...\""])[25:";"]
[19:"        }\n"]        if [2:"("]args.length == 0[2:")"] [27:"{"]
                [28:"System.out."]println([29:"\"...\""])[30:";"]
        [31:"System.out."]println([32:"\"...\""])[33:";"]
        [27:"} "]else [34:"{"]
                [35:"System.out."]println([36:"\"Success\""])[37:";"]
[34:"        }\n"]        if [3:"("]args.length > 0[3:")"] [39:"{"]
                [40:"System.out."]println([41:"\"Terminating\""])[42:";"]
        [39:"} "]else [43:"{"]
                [44:"System.out."]println([45:"\"Terminating\""])[46:";"]
        [47:"System.out."]println([48:"\"...\""])[49:";"]
[43:"        }\n"]        for [4:"("][51:"String"] arg : args[4:")"] [52:"{"]
                [53:"System.out."]println(arg)[54:";"]
[52:"        }\n"]        [5:"int"] i = 0[6:";"]
        for [7:"("][58:"String"] arg : args[7:")"] [59:"{"]
                [60:"System.out."]println(i++)[61:";"]
        [62:"System.out."]println(arg)[63:";"]
[59:"        }\n"]        while [8:"("]true[8:")"] [65:"{"]
                [66:"System.out."]println([67:"\"...\""])[68:";"]
        break[69:";"]
[65:"        }\n"]        while [9:"("]true[9:")"] [71:"{"]
        break[72:";"]
[71:"        }\n"]        try [10:"{"]
                [74:"System.out."]println([75:"\"...\""])[76:";"]
        [10:"} "]catch [11:"("]Exception e[11:")"] [12:"{"]
                e.printStackTrace()[79:";"]
[12:"        }\n"]        try [13:"{"]
                [81:"System.out."]println([82:"\"...\""])[83:";"]
        [84:"System.out."]println([85:"\"...\""])[86:";"]
        [13:"} "]catch [14:"("]Exception e[14:")"] [15:"{"]
                [89:"System.out."]println([90:"\"...\""])[91:";"]
        e.printStackTrace()[92:";"]
[15:"        }\n"]        do [94:"{"]
                [95:"System.out."]println([96:"\"...\""])[97:";"]
        break[98:";"]
        [94:"} "]while [16:"("]true[16:")"][99:";"]
        do [101:"{"]
        break[102:";"]
        [101:"} "]while [17:"("]true[17:")"][103:";"]
    }
}
