[versions]
# libraries
annotations = "24.1.0"
jsoup = "1.17.2"
junit = "5.11.0-M2"
jackson = "2.17.2"
jsr305 = "3.0.2"
pioneer = "2.2.0"

# plugins
kotlin = "1.9.24"
changelog = "2.2.1"
gradleIntelliJPlugin = "1.17.4"
qodana = "0.1.13"
kover = "0.7.6"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
jackson-dataformat-toml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-toml", version.ref = "jackson" }
jsr305 = { group = "com.google.code.findbugs", name = "jsr305", version.ref = "jsr305" }
junit-pioneer = { group = "org.junit-pioneer", name = "junit-pioneer", version.ref = "pioneer" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
