name: Bug Report
description: Report incorrect folding behavior
title: "Bug: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue with Advanced Expression Folding!
  - type: textarea
    id: reason
    attributes:
      label: Why is this a bug?
      description: Explain why the current folding is incorrect.
      placeholder: |
        The folding changes the code's meaning / makes it less readable because...
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Code sample
      description: Minimal snippet that reproduces the bug.
      render: java
      placeholder: |
        class Example {
            void method() {
                // your code
            }
        }
    validations:
      required: false
  - type: textarea
    id: actual
    attributes:
      label: Current folding
      description: What does the plugin fold the snippet into? Paste the folded result or describe it.
      render: java
      placeholder: |
        class Example {
            void method() {
                // folded result
            }
        }
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected folding
      description: How should the snippet be folded instead?
      render: java
      placeholder: |
        class Example {
            void method() {
                // expected folding
            }
        }
    validations:
      required: false
  - type: input
    id: plugin_version
    attributes:
      label: Plugin Version
      description: Which version of the plugin are you using?
    validations:
      required: false
  - type: input
    id: ide_version
    attributes:
      label: IDE Version
      description: e.g. IntelliJ IDEA 2025.2
    validations:
      required: false
  - type: checkboxes
    id: checks
    attributes:
      label: Verification
      options:
        - label: I have tested with the latest plugin release
          required: false
        - label: I'd like to help fix this bug
          required: false
