name: Build and Test on Multiple Operating Systems
on:
  push:
    branches-ignore:
      - "master"
  pull_request:
    branches-ignore:
      - "master"
  schedule:
    - cron: '24 14 * * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            test: ./gradlew test
          - os: macos-latest
            test: ./gradlew test
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-home-cache-cleanup: true

      - name: Run tests
        run: ${{ matrix.test }}
