name: Integration Tests

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  integrationTest:
    runs-on: ${{ matrix.os }}
    env:
      integration: '1'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 17

      - name: Build plugin
        shell: bash
        run: ./gradlew buildPlugin

      - name: Install UI test dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xvfb \
            libxi6 \
            libxtst6 \
            libgtk-3-0 \
            libdbus-glib-1-2 \
            dbus-x11

      - name: Start virtual display
        if: runner.os == 'Linux'
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          echo "DISPLAY=:99" >> $GITHUB_ENV
          sleep 3

      - name: Run IDE integration tests
        run: ./gradlew test

      - name: Upload integration artifacts
        if: always()
        id: upload_artifacts
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-artifacts-${{ matrix.os }}
          path: |
            out/ide-tests/logs
            out/ide-tests/tests/**/log/**
            out/ide-tests/tests/**/screenRecording/**
            out/ide-tests/tests/**/screenshots/**
            out/ide-tests/tests/**/driver/**
          if-no-files-found: warn

      - name: Publish artifact download link
        if: always() && steps.upload_artifacts.outputs.artifact-url != ''
        env:
          ARTIFACT_URL: ${{ steps.upload_artifacts.outputs.artifact-url }}
        run: |
          {
            echo "## Integration test artifacts"
            echo
            echo "[Download results zip](${ARTIFACT_URL})"
          } >> "$GITHUB_STEP_SUMMARY"
