name: "Pull Request Labeler"
on:
  pull_request_target:
  workflow_dispatch:
    inputs:
      pr-number:
        description: 'PR number to label'
        required: false

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v6.0.1
      with:
        sync-labels: false
        pr-number: ${{ github.event.inputs.pr-number }}
