name: TODO Run Integration Tests
permissions:
  contents: read

on: [workflow_dispatch]

jobs:
  integrationTest:
    runs-on: ${{ matrix.os }}
    env:
      integration: '1'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 17

      - name: Build plugin
        shell: bash
        run: ./gradlew buildPlugin

      - name: Setup Display (Linux)
        if: runner.os == 'Linux'
        uses: coactions/setup-xvfb@v1
        with:
          run: ./gradlew check
